apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: piggymetrics
  labels:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/component: accounts
    app.kubernetes.io/part-of: piggymetrics
spec:
  type: ClusterIP
  ports:
    - port: 6000
      targetPort: 6000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/part-of: piggymetrics
