apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: piggymetrics
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: notifications
    app.kubernetes.io/part-of: piggymetrics
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: piggymetrics
